/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as DialDataRouteImport } from './routes/dial-data'
import { Route as IncentivesRouteImport } from './routes/incentives'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LeaveRouteImport } from './routes/leave'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns.$campaignId'
import { Route as EmployeesIndexRouteImport } from './routes/employees.index'
import { Route as EmployeesEmployeeIdRouteImport } from './routes/employees.$employeeId'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const DialDataRoute = DialDataRouteImport.update({
  id: '/dial-data',
  path: '/dial-data',
  getParentRoute: () => rootRouteImport,
} as any)
const IncentivesRoute = IncentivesRouteImport.update({
  id: '/incentives',
  path: '/incentives',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRoute = LeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesEmployeeIdRoute = EmployeesEmployeeIdRouteImport.update({
  id: '/employees/$employeeId',
  path: '/employees/$employeeId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/attendance': typeof AttendanceRoute
  '/dial-data': typeof DialDataRoute
  '/incentives': typeof IncentivesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/notifications': typeof NotificationsRoute
  '/performance': typeof PerformanceRoute
  '/quality': typeof QualityRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/attendance': typeof AttendanceRoute
  '/dial-data': typeof DialDataRoute
  '/incentives': typeof IncentivesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/notifications': typeof NotificationsRoute
  '/performance': typeof PerformanceRoute
  '/quality': typeof QualityRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/employees': typeof EmployeesIndexRoute
  '/leads': typeof LeadsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/attendance': typeof AttendanceRoute
  '/dial-data': typeof DialDataRoute
  '/incentives': typeof IncentivesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/notifications': typeof NotificationsRoute
  '/performance': typeof PerformanceRoute
  '/quality': typeof QualityRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-insights'
    | '/attendance'
    | '/dial-data'
    | '/incentives'
    | '/leaderboard'
    | '/leave'
    | '/login'
    | '/mcp'
    | '/notifications'
    | '/performance'
    | '/quality'
    | '/reports'
    | '/settings'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/campaigns/$campaignId'
    | '/employees/$employeeId'
    | '/leads/$leadId'
    | '/campaigns/'
    | '/employees/'
    | '/leads/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-insights'
    | '/attendance'
    | '/dial-data'
    | '/incentives'
    | '/leaderboard'
    | '/leave'
    | '/login'
    | '/mcp'
    | '/notifications'
    | '/performance'
    | '/quality'
    | '/reports'
    | '/settings'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/campaigns/$campaignId'
    | '/employees/$employeeId'
    | '/leads/$leadId'
    | '/campaigns'
    | '/employees'
    | '/leads'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/ai-insights'
    | '/attendance'
    | '/dial-data'
    | '/incentives'
    | '/leaderboard'
    | '/leave'
    | '/login'
    | '/mcp'
    | '/notifications'
    | '/performance'
    | '/quality'
    | '/reports'
    | '/settings'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/campaigns/$campaignId'
    | '/employees/$employeeId'
    | '/leads/$leadId'
    | '/campaigns/'
    | '/employees/'
    | '/leads/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiInsightsRoute: typeof AiInsightsRoute
  AttendanceRoute: typeof AttendanceRoute
  DialDataRoute: typeof DialDataRoute
  IncentivesRoute: typeof IncentivesRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LeaveRoute: typeof LeaveRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  NotificationsRoute: typeof NotificationsRoute
  PerformanceRoute: typeof PerformanceRoute
  QualityRoute: typeof QualityRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute
  EmployeesEmployeeIdRoute: typeof EmployeesEmployeeIdRoute
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dial-data': {
      id: '/dial-data'
      path: '/dial-data'
      fullPath: '/dial-data'
      preLoaderRoute: typeof DialDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incentives': {
      id: '/incentives'
      path: '/incentives'
      fullPath: '/incentives'
      preLoaderRoute: typeof IncentivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/': {
      id: '/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/$employeeId': {
      id: '/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof EmployeesEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiInsightsRoute: AiInsightsRoute,
  AttendanceRoute: AttendanceRoute,
  DialDataRoute: DialDataRoute,
  IncentivesRoute: IncentivesRoute,
  LeaderboardRoute: LeaderboardRoute,
  LeaveRoute: LeaveRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  NotificationsRoute: NotificationsRoute,
  PerformanceRoute: PerformanceRoute,
  QualityRoute: QualityRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
  EmployeesEmployeeIdRoute: EmployeesEmployeeIdRoute,
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
  LeadsIndexRoute: LeadsIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
